/*export const FILTER_BY_TOPIC = "FILTER_BY_TOPIC";
export const CHANGE_TOP_NAV_CONTROL_STATE = "CHANGE_TOP_NAV_CONTROL_STATE";*/

export const SET_NAVIGATION_ACTIVE_ITEM = "SET_NAVIGATION_ACTIVE_ITEM";
